version: "3"

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./src/db/mysql_data:/var/lib/mysql
  web:
    build: .
    depends_on:
      - db
    ports:
      - "3000:3000"
    volumes:
      - ./src:/docker-rails-test

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    depends_on:
      - web
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./src/public:/docker-rails-test/public
volumes:
  db-data:
