services:
  db:
    build: ./infra/dev/db
    environment:
      TZ: Asia/Tokyo
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./src/db/mysql_data:/var/lib/mysql
  app:
    build:
      context: .
      dockerfile: ./infra/dev/app/Dockerfile
    depends_on:
      - db
    ports:
      - "3000:3000"
    volumes:
      - ./src:/docker-rails-test

  web:
    build: ./infra/dev/web
    ports:
      - "80:80"
    depends_on:
      - app
    volumes:
      - ./infra/dev/web/default.conf:/etc/nginx/conf.d/default.conf
      - ./src/public:/docker-rails-test/public
volumes:
  db-data:
