# ベースイメージ
FROM nginx:latest

# 設定ファイルのコピー
# COPY ./infra/prod/web/default.conf /etc/nginx/conf.d/default.conf

# SSL証明書の設定（例）
# COPY ./path/to/your/certificates/domain.crt /etc/nginx/certs/domain.crt
# COPY ./path/to/your/certificates/domain.key /etc/nginx/certs/domain.key
